export class CodeHighlight {
  keyword: ResourceColor = '#b15ef2' // 关键字
  method: ResourceColor = '#ff0d7aa2' // 方法名
  type: ResourceColor = '#9333ea' // 类型
  modifier: ResourceColor = '#4169e1' // 修饰符
  constant: ResourceColor = '#8b0000' // 常量
  variable: ResourceColor = '#333333' // 变量
  operator: ResourceColor = '#b22222' // 运算符
  punctuation: ResourceColor = '#666666' // 标点
  brace: ResourceColor = '#ff794d4d' // 括号
  bigBrace: ResourceColor = '#D17E9B' //大括号
  string: ResourceColor = '#ff946bdd' // 字符串
  number: ResourceColor = '#B17425' // 数字
  boolean: ResourceColor = '#b15ef2' // 布尔值
  nullish: ResourceColor = '#ffaca645' // 空值
  promise: ResourceColor = '#b15ef2' // Promise
  tag: ResourceColor = '#008b8b' // HTML标签
  attrName: ResourceColor = '#ffc65e0a' // 属性名
  attrValue: ResourceColor = '#ff50641c' // 属性值
  doctype: ResourceColor = '#ff8c00' // 文档声明
  comment: ResourceColor = '#ff787983' // 注释
  decorator: ResourceColor = '#A05E16' // ArkTS 装饰器
  component: ResourceColor = '#20b2aa' // ArkTS UI组件
  normal: ResourceColor = '#ff575a66' // 普通文本
}